# Generated by Django 6.0 on 2026-04-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='solution',
            field=models.TextField(blank=True),
        ),
    ]
